---
- hosts: 127.0.0.1
  user: vagrant
  become: yes
  tasks:
  - name: Apt install common packages
    apt: pkg={{ item }} force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - python3-dev
      - libmysqlclient-dev
      - uwsgi-plugin-python3

######################################################
# docker
######################################################

  - name: Remove old docker package
    apt: pkg={{ item }} autoremove=yes purge=yes force=yes update_cache=yes state=absent
    with_items:
      - docker
      - docker-engine
      - docker.io

  - name: Apt install dep packages
    apt: pkg={{ item }} force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common

  - name: Add an Apt signing key to a specific keyring file
    apt_key:
      id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable
      state: present

  - name: Apt install docker-ce
    apt: pkg={{ item }} force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - docker-ce

######################################################
# python requirements
######################################################

  - name: Install global python requirements
    pip: name={{item}} executable=pip3
    with_items:
      - django
      - mysqlclient
      - uwsgi

######################################################
# uwsgi demon
######################################################

  - name: uwsgi ini file directory
    file: path=/etc/uwsgi state=directory owner=root group=root mode=0755

  - name: vassals directory
    file: path=/etc/uwsgi/vassals state=directory owner=root group=root mode=0755

  - name: emperor ini file
    copy: src=emperor.ini dest=/etc/uwsgi/emperor.ini

  - name: uwsgi ini file
    copy: src=uwsgi.ini dest=/etc/uwsgi/vassals/uwsgi.ini

  - name: uwsgi demon
    copy: src=uwsgi.service dest=/etc/systemd/system/uwsgi.service

  - name: uwsgi demon start
    service: name=uwsgi state=started

  - name: uwsgi demon enable
    service: name=uwsgi enabled=yes

######################################################
# nginx install
######################################################

  - name : Add official nginx PGP key
    apt_key:
      url: http://nginx.org/keys/nginx_signing.key
      state: present

  - name : Add official nginx repository
    lineinfile : >
      dest=/etc/apt/sources.list
      line='{{item}} http://nginx.org/packages/ubuntu/ {{ansible_distribution_release}} nginx'
    with_items:
      - deb
      - deb-src
    register: update_apt

  - name: Update apt
    apt: update_cache=yes
    when: update_apt is defined and update_apt.changed == True

  - name: Apt install nginx
    apt: pkg={{ item }} force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - nginx

  - name: nginx start
    service: name=nginx state=started

  - name: nginx demon enable
    service: name=nginx enabled=yes

  - name: nginx conf file
    copy: src=default.conf dest=/etc/nginx/conf.d/default.conf

  - name: nginx conf file
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf

