---
- hosts: 127.0.0.1
  user: vagrant
  sudo: yes
  tasks:
  - name: Apt install common packages
    apt: pkg={{ item }} force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - git
      - python3-dev
      - nkf
      - colordiff
      - mysql-client
      - libmysqlclient-dev

  - name: Remove old docker package
    apt: pkg={{ item }} autoremove=yes purge=yes force=yes update_cache=yes state=absent
    with_items:
      - docker
      - docker-engine
      - docker.io

  - name: Apt install dep packages
    apt: pkg={{ item }} force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common

  - name: Add an Apt signing key to a specific keyring file
    apt_key:
      id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable
      state: present

  - name: Apt install docker-ce
    apt: pkg={{ item }} force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - docker-ce

  - name: Install global python requirements
    pip: name={{item}} executable=pip3
    with_items:
      - django
      - mysqlclient
      - uwsgi

