---
- hosts: 127.0.0.1
  user: vagrant
  sudo: yes
  tasks:
  - name: Apt install common packages
    apt: pkg={{ item }} force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - git
      - nkf
      - colordiff
      - mysql-client

  - name: Remove old docker package
    apt: pkg={{ item }} autoremove=yes purge=yes force=yes update_cache=yes state=absent
    with_items:
      - docker
      - docker-engine
      - docker.io

  - name: Apt install dep packages
    apt: pkg={{ item }} force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common

